import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Image from "next/image";

const Home = () => {
  return (
    <div className="no-scrollbar">
      <Head>
        <title>Chat-App</title>
        <meta name="Chat-App" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/login-picture.jpg"
        layout="fill"
        className="absolute w-full h-full object-cover mix-blend-overlay"
        alt="Young people next to a laptop."
      />
      <Sidebar />
    </div>
  );
};
export default Home;
