import Head from "next/head";
import Sidebar from "../components/Sidebar";

const Home = () => {
  return (
    <div className="no-scrollbar">
      <Head>
        <title>Chat-App</title>
        <meta name="Chat-App" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </div>
  );
};
export default Home;
